refactor: share Meridian config
filecoin-station/spark-api pull request #71
Opened 2023-09-06 13:05 UTC by bajtos

Rework spark-api to use the contract configuration from spark-publish.

2023-09-07 10:16 UTC, juliangruber requested changes

2023-09-07 10:16 UTC, juliangruber commented on spark-publish/ie-contract-config.js
I don't think `spark-publish` should own the contract. It is a sub project of `spark-api`, and both need access to the contract. Therefore I think the contract should be either owned by `spark-api` or none (a separate project)

2023-09-11 06:31 UTC, bajtos commented on spark-publish/ie-contract-config.js
I see your point. Moving the contract to a different place requires complex changes, because spark-publish's Dockerfile is rooted inside spark-publish directory and does not have access to other files in this repo.

The way I am looking at this:
- spark-publish is interacting with the contract (submitting measurements), therefore it makes sense to me that spark-publish owns the contract config
- spark-api wants to listen for events created by the contract used by spark-publish, therefore it's ok to load contract config from spark-publish

Anyhow, I am fine to move the contract config to a new directory shared by both spark-api and spark-publish, if you think it's worth the extra effort.

2023-09-11 09:50 UTC, juliangruber commented on spark-publish/ie-contract-config.js
Ok, let's keep it like this, knowing we both want to refactor in the future, once the need arises

2023-09-11 09:50 UTC, juliangruber approved these changes

2023-09-12 06:32 UTC, merged